<!DOCTYPE html>
 
<html lang="es">
 
<head>
<title>Page Not Found</title>
<meta name="robots" content="noindex, nofollow" />
<meta charset="utf-8" />
<style>
.nb-error {
  margin: 0 auto;
  text-align: center;
  max-width: 480px;
  padding: 60px 30px;
}

.nb-error .error-code {
  color: #2d353c;
  font-size: 96px;
  line-height: 100px;
}

.nb-error .error-desc {
  font-size: 12px;
  color: #647788;
}
.nb-error .input-group{
  margin: 30px 0;
}
</style>
</head>
 
<body>
	<div class="nb-error">
		  <div class="error-code">404</div>
		  <h3 class="font-bold">No encotramos esta p&aacute;gina.</h3>

		  <div class="error-desc">
			  La p&aacute;gina que buscas no la encontramos o no existe. <br/>
			 <ul class="list-inline text-center text-sm">
			   <li class="list-inline-item">
					<a href="/users/" class="text-muted">Ir a p&aacute;gina principal</a>
			   </li>
			</ul>
			<div class="text-center">
		   </div>
		  </div>
	  </div>
</body>
</html>